### PR TITLE
Fix enum names to conform to Swift 3 syntax

### PR DESCRIPTION
**Pull request by Liquidsoul**
* [x] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself
  * [x] Add the entry in the appropriate section (Bug Fix / Nw Feature / Breaking Change / Internal Change)
  * [x] Add a period and 2 spaces at the end of your short entry description
  * [x] Add links to your GitHub profile to credit yourself and to the related PR and issue after your description

---

This fixes the swiftlint errors reported in #296 without addressing the CI reporting issue.

### CODE REVIEW

**Comment by djbe** [comment]
@AliSoftware do you mean increasing the swiftlint version on CI?

**Comment by AliSoftware** [comment]
Yeah, I think it would be worth ensuring we all have the same swiftlint version, both all of us and CI.

That would mean:
 - Increasing the swiftlint version on CI
 - Maybe in the `rake code:lint` and Build Phase, adding a check to ensure, in addition to `swiftlint` being installed, if it's the expected version?

**Comment by AliSoftware** [comment]
Let's merge this and fix CI / swiftlint version sync later

**Comment by Liquidsoul** [comment]
@djbe I've updated the changelog entry to reference this PR

**Comment by AliSoftware** [comment]
@Liquidsoul Thx for the PR btw.

Seing that you named your branch just `enumNames` that makes me wonder if we should use some convention for the branch names?

* We usually use `feature/*` for branches adding features, and sometimes for branches fixing stuff too
* It would be more consistent to name our branches `fix/*` for fixes to make them different from feature branches
* I started naming some branches `feature/breaking/*` for features that have to wait for the new major version to be merged because they are API-breaking. This helps differentiate major breaking features from standard ones.

**Comment by Liquidsoul** [comment]
Fine by me. I'll do that from now on 👌

**Pull request merged**
