### PR TITLE
Fix Swift version for swiftenv #trivial

### PR DESCRIPTION
**Pull request by usami-k**
Fix build error on swiftenv environment.

```
$ swiftenv versions
* 4.0 (set by /Users/usami/repo/github.com/SwiftGen/SwiftGen/.swift-version)
  4.1
  4.1.2
  4.2
$ swift package --version
Swift Package Manager - Swift 4.0.0-dev
$ swift build
error: package at '/Users/usami/repo/github.com/SwiftGen/SwiftGen' requires a minimum Swift tools version of 4.2.0 (currently 4.0.0)
```

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AliSoftware** [comment]
Thanks for this PR !

Might be a good occasion to unit-test that. That means either write tests that ensure the content of `.swift-version` match what we have in our Rakefiles & all, or edit the `.circleci/config.yml` file to build using SPM in Xcode 10…

**Comment by djbe** [comment]
I think we can just merge this, and at some later point write some checks using danger (or in our release version checks) to ensure the swift version is the same everywhere.

> edit the .circleci/config.yml file to build using SPM in Xcode 10
I'm not sure what this is supposed to mean?

**Comment by AliSoftware** [comment]
I think back in the day I meant "make the CI build SwiftGen using `swift build`, so that this error is caught by the CI"

Agreed to merge it right away though

**Comment by djbe** [comment]
The thing about that is that the swift version in CI is set by the macos/xcode image we use. We don't use `swiftenv`, so it'll never affect us. That's why I suggested the danger/release check.

**Comment by AliSoftware** [comment]
Ohhh right 👍 good point

**Pull request merged**
