### PR TITLE
Support Swift Package plugins: Add artifactbundle to release assets

### PR DESCRIPTION
**Pull request by AliSoftware**
> **Warning** Do not merge: this Draft PR was only created to run CI checks from a PR that came from a fork.

This PR was created by pulling the content of [#926](https://github.com/SwiftGen/SwiftGen/pull/926) in the main repo — instead of being from @nicorichard 's fork — by running `git pull git@github.com:nicorichard/SwiftGen.git develop_artifact_bundle` into this newly created branch. This was done so that CI can run without any security issue (because Danger can't run on forks for security reasons, and only works on PRs that are from this repo) and so that the Danger CI step could analyse and validate the PR.

Once all the warnings found by Danger have been addressed in #926, we should land #926 and close this Draft PR (because 926 is where all the GitHub discussions are).

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AliSoftware** [comment]
@nicorichard the process I recommend to move forward with your PR https://github.com/SwiftGen/SwiftGen/pull/926 is the following:
 - Fix the violations and push your fix in your fork (since that's where the code for your PR comes from), which will update https://github.com/SwiftGen/SwiftGen/pull/926
 - Then, switch to the `nicorichard/artifact-bundle` branch **from the main repo/remote** — i.e. the head branch of _this_ PR —, and pull your fork's fix in it, by running `git pull git@github.com:nicorichard/SwiftGen.git develop_artifact_bundle`. This will update this PR #953 with your fix, and as a result, re-trigger the Danger CI step, which will update the PR's checks… on both PRs
 - After Danger has finished running in this PR, it should have updated the CI checks in _both_ PRs, and thus (assuming Danger then goes green), you should be able to merge your PR #926 as initially intended. You should have the necessary permissions to merge that PR yourself once all checks go green.
 - And finally, you can close this draft PR #963

PS: The reason I suggest to continue working on your fork to land the fix — and only use this PR #953 as a kind of "helper" to trigger Danger CI — as opposed to directly fix the Danger violation in this very PR, is mostly for style and consistency, because most of the discussions that happened around your feature were in #926, and that's also what you reference in the `CHANGELOG.md` (and rightfully so), so it makes more sense to me that would be the one to land, as oppose to this one.

**Comment by djbe** [comment]
Did I miss something? Danger didn't turn green here, and it's still based on NIco's own fork instead of our repo.

**Comment by AliSoftware** [comment]
@djbe  This is indeed strange, because the Danger comment itself, on the other hand, _was_ updated to say "Seems like everything is in order 👍 You did a good job here! 🤝" and removed the previous violation now that 6832452 addressed it… so I'm not sure why the CI check itself still shows ❌  while the comment was clearly updated to match a green status (i.e. no violation) 🤔

**Comment by AliSoftware** [comment]
@djbe Ok we think what might have happened here is a race condition on GitHub Actions, where it ran on both PRs, but (1) finished running on this PR first, and updated the Danger comment above to confirm there were no violations anymore, and marked the CI check as passed ✅ … (2) only then did it finish running on the other PR… which made it fail (because of it being from a fork = secret not exposed), and update the CI check status to ❌ , overriding the last ✅  status reported from previous successful run.

At least that seems like the most plausible explanation to me, given that the Danger comment was updated to say everything was good.

Notice that the way GitHub withs, CI status checks are attached to a commit SHA1. So if a status check passes or fails on a specific commit, _every_ PR whose top commit is that SHA1 will have their CI status check updated with the new status. This is what made it possible for me to create this PR to have the Danger run… but still report its status on both this PR and the other one… but also what could cause race conditions in status check reporting.

**Comment by djbe** [comment]
Yeah did notice the Eve bot message, but just wanted to check 👍

**Comment by AliSoftware** [comment]
We'll now let @nicorichard try to do his first new release of SwiftGen to include that new fix in it, as a brand new co-Maintainer of SwiftGen… hopefully it will go well, if not don't hesitate to ask for help on the process here (I'll go to sleep soon then on vacation for a couple of weeks starting tomorrow, but I'm sure David can help if you're stuck and need some pointers)

**Pull request merged**
