### PR TITLE
🚧 WIP 🚧 SwiftGen 5.0.0 release

### LINKED ISSUE #312: SwiftGen 5.0.0
Right, so we're nearing the point to release SwiftGen 5.0, the remain issues to tackle are:

### Breaking PRs
- [x] Merge "unify storyboard templates" (https://github.com/SwiftGen/templates/pull/57)
- [x] Merge "font templates refactor" (https://github.com/SwiftGen/templates/pull/58)
- [x] Merge "parser protocol" (https://github.com/SwiftGen/SwiftGenKit/pull/46)
- [x] Merge "swiftlint version check" (https://github.com/SwiftGen/Eve/pull/9) and propagate it to the other repos
- [x] Remove old CLI options (#301)
- [x] Update documentation/templates (#305, https://github.com/SwiftGen/templates/pull/59)
### Releases
- [x] Release StencilSwiftKit 2.0 (https://github.com/SwiftGen/StencilSwiftKit/pull/55)
- [x] Release SwiftGenKit 2.0 (https://github.com/SwiftGen/SwiftGenKit/pull/48)
- [x] Update SwiftGen to match SwiftGenKit changes (#313)
- [x] Create & merge a PR for "rename some subcommands" (#311, propagate to templates repo)
- [x] Release templates 2.0
### Documentation
- [x] Update SwiftGen documentation with new commands/options/templates and sample output (#314)
- [x] Review/Update SwiftGen README (#318)
- [x] Update Playground code (#319)
- [x] Write a general migration guide (#320)
- [x] Check on each repo that we didn't forget any `CHANGELOG` entries esp after the last PRs we did recently in a rush (#321)
- [x] Write a changelog entry that includes the major items from the other repositories (#321)
- [x] Update wiki if needed

### And finally…
- [x] Check that the submodule for each repo points to `master` (#321)
- [x] Check that it isn't necessary to move the 2.0.0 tags for `SwiftGenKit` & `StencilSwiftKit` after all those last-minute hot fixes?
- [ ] Quick test installing and using `swiftgen` locally (as we still don't have unit test for the CLI layer), like `rake cli:install` + `./build/swiftgen/bin/swiftgen -v`, `./build/swiftgen/bin/swiftgen list templates`, etc
- [ ] Release SwiftGen 5.0 (#321)
- [ ] `rake changelog:reset` on all repos

### PR DESCRIPTION
**Pull request by AliSoftware**
Fixes #312.

This is a first commit to work on the 5.0 CHANGELOG. It's a bit early to open this as there are still some boxes to check in #312, but let make this evolve to work on the CHANGELOG at first.

We could then later rebase this PR (especially once #320 is merged) and continue to add all the necessary commits (align submodules, changes in podspecs, etc.) once we really are ready to release.

### CODE REVIEW

**Comment by AliSoftware** [comment]
NB: We'll also use this PR to amend SwiftGen's CHANGELOG to add key/breaking points from other repos, haven't started that yet (don't hesitate to add commits to that branch)

_All the points we listed in the Migration Guide could be a good reference to know which breaking changes from other repos we want to absolutely mention in the master CHANGELOG._

**Comment by djbe** [comment]
I also fixed some of the changelog issue urls were incorrect in the other repos, someone should double check them. After all the migration guides and changelogs for the other repos are ready, do we want to move the tags for them?

**Comment by AliSoftware** [comment]
I've un `rake changelog:check` and according to it all links seem to be ok (or well-formatted at least) now 👍 

Looking at other CHANGELOGs, I don't think there's much more entries from them to report to the master CHANGELOG, the ones you've reported here seem like the most important ones to me 👌

**Comment by AliSoftware** [comment]
I'll then take a stab a SwiftGenKit's MG to make it a little nicer. Then I'll update the "Migration Guide" wiki entry to point to the md files.

We should indeed then check if we should move other repos' tags. Or minor-bump them if changes are more than just docs?

After all that and checking the submodules are aligned, we should be ready to bump SwiftGen's own version and go live at last ;)

**Comment by djbe** [comment]
Whichever is easiest TBH, the only changes have been to migration guides and changelogs (except for a linux compilation issue for StencilSwiftKit).

**Comment by AliSoftware** [comment]
Steps to finish that release:

* [ ] Review https://github.com/SwiftGen/SwiftGenKit/issues/50 & merge it
* [ ] Realign all submodules to master
* [ ] Generate new 2.0.1 tags for SwiftGenKit/StencilSwiftKit/templates
* [ ] Update SwiftGen.podspec, `rake install` it and use it for a quick test drive (as we don't have unit tests for the CLI layer yet)
* [ ] Release to CP & Homebrew
* [ ] Reset CHANGELOGs with new empty Master entries

**Comment by djbe** [comment]
The wiki page is ok, I only changed the order so that the newer version (5.0) is on top.

**Pull request merged**
