### PR TITLE
Fix wrong link in CHANGELOG

### PR DESCRIPTION
**Pull request by AliSoftware**
* [X] I've started my branch from the `develop` branch (gitflow)
* [X] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself
  * well…

---

 - CHANGELOG entry was pointing to PR 529 instead of 530
 - Missing trailing two spaces at end of one of the entries

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖
Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AliSoftware** [comment]
@djbe wondering if we should merge that to master too… (= consider it as a "hotfix" branch in gitflow)?

**Comment by djbe** [comment]
Sure, but the PR should start from master then, not from develop.

**Comment by AliSoftware** [comment]
Yeah, that's why I asked. I will do a real hotfix branch then (starting from master, merged to master+develop).

Officially when we do a hotfix in gitflow, that generates a new tag and version at the end, I'll just not do that as we don't need a 6.0.2 just for that, but we'll still follow the branching logic, just not tag

**Comment by djbe** [comment]
Sounds good :+1:

**Comment by AliSoftware** [comment]
Ok, was gonna re-start this from master to do a hotfix… but given we'll release a 6.0.2 again pretty soon it seems, not sure if it's worth the effort to make the git tree a 🍝 just for that ^^

**Comment by djbe** [comment]
Yeah just merge it into develop, might as well.

**Pull request merged**
