### PR TITLE
Introduce `plist` command

### PR DESCRIPTION
**Pull request by toshi0383**
## What
Introduces easy and even type-safe access to Info.plist.
e.g. `InfoPlist[.CFBundleIdentifier] // String`

All types you can choose on Xcode's plist editor is supported.
- String
- Int
- Bool
- Data
- Date
- Array
- Dictionary

## Type Inference
Type is inferred at first level. So contents of dictionary or array remain ambiguous(Any).

InfoPlist[.NSAppTransportSecurity] // [String: Any]
InfoPlist[.UIRequiredDeviceCapabilities] // [Any]

See https://github.com/SwiftGen/SwiftGen/pull/288#issuecomment-295506027 for discussion.

## Why
Being part of the iOS community, I've seen a lot of different ways to access app's info in different projects. e.g. AppConfig.swift, AppInfo.swift, Config.swift... and so on.
Neither of them did not really guarantee the resource existence (or even hard-coded).
I thought about creating a new library like `SwiftyInfoPlist` (like SwiftyUserDefaults) but it turns out SwiftGen is more suitable. Because when the resource and code is separated, well, that's exactly what SwiftGen is made for!

## Usage
```
$ swiftgen plist path-to/Info.plist
// Generated using SwiftGen, by O.Halligon — https://github.com/SwiftGen/SwiftGen
import Foundation

private let _Plist = Bundle(for: _InfoPlist.self).infoDictionary!
let InfoPlist = _InfoPlist()

private func castOrFail<T>(_ any: Any?) -> T {
  guard let t = any as? T else {
    fatalError("Couldn't cast value to type \(T.self)")
  }
  return t
}

class _InfoPlist {
  subscript(key: StringKey) -> String {
    return castOrFail(_Plist["\(key)"])
  }
  subscript(key: IntKey) -> Int {
    return castOrFail( _Plist["\(key)"])
  }
  // Int64 for 32bit device compatibility
  // e.g. On 32bit device, Int is Int32 where on 64bit device, it's Int64.
  subscript(key: IntKey) -> Int64 {
    return castOrFail(_Plist["\(key)"])
  }
  subscript(key: BoolKey) -> Bool {
    return castOrFail(_Plist["\(key)"])
  }
  subscript(key: DictKey) -> [String: Any] {
    return castOrFail(_Plist["\(key)"])
  }
  subscript(key: ArrayKey) -> [Any] {
    return castOrFail(_Plist["\(key)"])
  }
  subscript(key: DataKey) -> Data {
    return castOrFail(_Plist["\(key)"])
  }
  subscript(key: DateKey) -> Date {
    return castOrFail(_Plist["\(key)"])
  }
}

enum StringKey: String {
  case UIUserInterfaceStyle = "UIUserInterfaceStyle"
  case CFBundleInfoDictionaryVersion = "CFBundleInfoDictionaryVersion"
  case CFBundleDevelopmentRegion = "CFBundleDevelopmentRegion"
  case CFBundleIdentifier = "CFBundleIdentifier"
  case CFBundleShortVersionString = "CFBundleShortVersionString"
  case CFBundleExecutable = "CFBundleExecutable"
  case UIMainStoryboardFile = "UIMainStoryboardFile"
  case CFBundlePackageType = "CFBundlePackageType"
  case CFBundleName = "CFBundleName"
  case CFBundleVersion = "CFBundleVersion"
}

enum IntKey: String {
  case SomeNumber = "SomeNumber"
}

enum BoolKey: String {
  case LSRequiresIPhoneOS = "LSRequiresIPhoneOS"
}

enum DataKey: String {
  case SomeData = "SomeData"
}

enum DateKey: String {
  case SomeDate = "SomeDate"
}

enum DictKey: String {
  case NSAppTransportSecurity = "NSAppTransportSecurity"
}

enum ArrayKey: String {
  case ArrayOfManyTypes = "ArrayOfManyTypes"
  case UIRequiredDeviceCapabilities = "UIRequiredDeviceCapabilities"
}
```

## Arbitrary Bundle Support
Bundle is instantiated using `init(for: Class)` initializer. 

Usage:
```bash
swiftgen plist /path/to/App/Info.plist -t swift3 --output AppsInfoPlistGen.swift # Add this to Main Bundle on Xcode
swiftgen plist /path/to/AppTests/Info.plist -t swift3 --output AppsTestsInfoPlistGen.swift # Add this to AppTests Bundle on Xcode
```

```swift
import XCTest
@testable import App

class PlistBundleTests: XCTestCase {
    func test001() {
        XCTAssertEqual(InfoPlist[.CFBundleIdentifier], "jp.toshi0383.AppTests")
        XCTAssertEqual(App.InfoPlist[.CFBundleIdentifier], "jp.toshi0383.App")
    }
}
```

### CODE REVIEW

**Comment by phatblat** [comment]
I love this idea, but this PR will need some cleanup before it's ready to be merged. I'll try to find some time to give a proper review.

**Comment by toshi0383** [comment]
Thanks for response!

> Please open PR for the related repository changes (templates and SwiftGenKit).

I did. Please look at them when you have time.🙏

**Comment by djbe** [comment]
I've reviewed the SwiftGenKit PR. 

I was wondering though: could we combine this Plist parser with the JSON parser from the codegen PR (#188)? Both essentially parse a dictionary of "stuff".

**Comment by toshi0383** [comment]
@djbe 
Thanks for the review!

> I was wondering though: could we combine this Plist parser with the JSON parser from the codegen PR (#188)? Both essentially parse a dictionary of "stuff".

I'd like to look into that in different PR, as a refactor. This PR at least "works", so for now we should think about if we can ship it or not.

**Comment by djbe** [comment]
While we could consider adding the JSON parser in a separate PR, I'd like to address the other items before merging (see https://github.com/SwiftGen/SwiftGenKit/pull/22#issuecomment-294627292)

**Comment by toshi0383** [comment]
Added Type Inference functionality. Users now can access Info.plist type-safe, too.
```swift
InfoPlist[.CFBundleIdentifier] // String
```
Type is inferred at first level. So contents of dictionary or array remain ambiguous(`Any`).
```swift
InfoPlist[.NSAppTransportSecurity] // [String: Any]
InfoPlist[.UIRequiredDeviceCapabilities] // [Any]
```
 Maybe I can support fine-grain type inference like this, but it would be too complicated.
```swift
// Note: Not Supported.
InfoPlist[.NSAppTransportSecurity][.NSExceptionDomains][.examplecom][.NSExceptionAllowsInsecureHTTPLoads] // Bool
```

I will update the description of this PR.

**Comment by toshi0383** [comment]
Added multiple Bundle support.

Usage:
```bash
swiftgen plist /path/to/App/Info.plist --output AppsInfoPlistGen.swift # Add this to Main Bundle on Xcode
swiftgen plist /path/to/AppTests/Info.plist --output AppsTestsInfoPlistGen.swift # Add this to AppTests Bundle on Xcode
```

```swift
import XCTest
@testable import App

class PlistBundleTests: XCTestCase {
    func test001() {
        XCTAssertEqual(InfoPlist[.CFBundleIdentifier], "jp.toshi0383.AppTests")
        XCTAssertEqual(App.InfoPlist[.CFBundleIdentifier], "jp.toshi0383.App")
    }
}
```

**Comment by djbe** [comment]
@toshi0383 Thank you for the update, sorry for the delay getting back to you.

My main feedback point would be: don't generate different arrays for each type. You can perfectly store this in an array, with each item having an key (string) and a valueType (generic). This also applies to the template. For example:

```swift
struct PlistKey<ValueType: Any> {
	let key: String
	let valueType = ValueType.self
}

enum InfoPlist {
  static let bundleIdentifier = PlistKey<Int>(key: "CFBundleVersion")

  subscript<ValueType: Any>(key: PlistKey<ValueType>) -> ValueType {
    ...
  }
}
```

Another (smaller) point: refrain from using force casts. Better to use something like:
```swift
guard let value = ... as? ValueType else {
  fatalError("Couldn't cast value to type \(ValueType)")
}
```

**Comment by AliSoftware** [comment]
> I was wondering though: could we combine this Plist parser with the JSON parser from the codegen PR (#188)? Both essentially parse a dictionary of "stuff".

I'd still prefer that we differentiate `swiftgen plist`, `swiftgen json` and ideally in the future `swiftgen yaml` as separate commands for now. We could merge them as one later (especially YAML being a superset of JSON we could imagine merging the two, even though most people don't know that YAML ∋ JSON)

**Comment by djbe** [comment]
Right, we could still unify the (internal) data structures, and how parts of the templates work, as they will do the same thing.

**Comment by AliSoftware** [comment]
Yeah, except that saying that I now realise that, even if YAML ∋ JSON in theory, we might use our future YAML dependency/library to parse actual YAML… but still use `NSJSONSerialization` to parse JSON (instead of using the YAML lib too for that), in case they have subtle implementation differences. 

That way, because people dealing with JSON are used to how `NSJSONSerialization` parses JSON and its possible edge cases, they'll not be surprised when they use `swiftgen json`, and it will still allow people to use `swiftgen yaml foo.json` to use the YAML parser as an alternative

**Comment by AliSoftware** [comment]
We might get some inspiration for the final solution of this template by using the [same ideas as `SwiftyUserDefaults`](https://github.com/radex/SwiftyUserDefaults/blob/master/Sources/SwiftyUserDefaults.swift#L186-L208) uses, which allows similar syntaxes at call site (`Defaults[.firstLaunch] // inferred as Bool` & `Defaults[.userName] // inferred as String`)

Like the template could generate all the  boilerplate code… + this extension (same idea as how SwiftyUserDefaults suggests to declare UserDefaults keys in your code):

```swift
extension PlistKeys {
    static let NSAppTransportSecurity = PlistKey<[String: Any]?>("NSAppTransportSecurity")
    static let CFBundleIdentifier = PlistKey<String>("CFBundleIdentifier")
}
```

Not sure how that compares to the currently implemented solution in this PR but I thought it could provide some inspiration.

**Comment by djbe** [comment]
Would it be possible (and interesting) to have type information for sub-items? (such as array items and dictionary items). Essentially a dot-syntax.

**Comment by AliSoftware** [comment]
Interesting, for sure! 
Possible? 🤔 Might be a little more complex 

Another solution is to generate a struct matching exactly the content of the Plist and make all its properties as  lazily computed variables?

**Comment by toshi0383** [comment]
Thanks for review!

@djbe 
> `subscript<ValueType: Any>`

This is not going to work, mate. Swift currently does not allow generic subscript.
Could you please actually apply a fix and confirm it works, before telling me to go back and fix the code? That way we'll have less confusion.😉 I perfectly welcome any suggestion or feedbacks, so you can even push to this branch if you need to.

> don't generate different arrays for each type. You can perfectly store this in an array, with each item having an key (string) and a valueType (generic).

In that case, generic parameter must be defined on initialization, so that is not going to work either.
I could go like key (string) and valueType (string), but it will cause me writing a lot of if-else in stencil template. I wanted it to be simple and just works.👍

> refrain from using force casts

Sure, I can improve that! 👌

**Comment by toshi0383** [comment]
@AliSoftware 

> the template could generate all the boilerplate code… + this extension (same idea as how SwiftyUserDefaults suggests to declare UserDefaults keys in your code):

I get your point.👀 I think it's cool too.. but `plist` command looks up every Info.plist key-value pairs anyways (to generate boilerplate code), so.. maybe we don't need that extension point, do we?

**Comment by toshi0383** [comment]
>  type information for sub-items

So maybe like this then?
```swift
InfoPlist[.NSAppTransportSecurity].NSExceptionDomains.examplecom.NSExceptionAllowsInsecureHTTPLoads // Bool
```
Or following standard code format conventions.. (I'm not sure if NSException... should be nsException... or nSException...)
```swift
InfoPlist[.NSAppTransportSecurity].nSExceptionDomains.examplecom.nSExceptionAllowsInsecureHTTPLoads // Bool
```

Question is, have anyone ever retrieved this value from Info.plist?😇
I'm just still not sure if it worth it to consider this complex feature. I thought main use-case of `plist` command is like simply retrieving a string URL for API endpoint.

**Comment by ealeksandrov** [comment]
Generating code from plist is not only about "Info.plist" but is also perfect for managing environment setting (API url, various API keys, etc).
See https://github.com/theappbusiness/ConfigGenerator as an example of stand-alone tool dedicated for this task.

It would be awesome to see similar functionality in SwiftGen. How can I help on this PR?

**Comment by toshi0383** [comment]
This PR is a bit outdated, so I'm closing for now.

**Pull request closed without merging**
