### PR TITLE
fix config lint not processing relative paths correctly

### PR DESCRIPTION
**Pull request by Lutzifer**
* [x] I've started my branch from the `develop` branch (gitflow)
  * [x] And I've selected `develop` as the "base" branch for this Pull Request I'm about to create
* [x] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself  
      _(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
  * [x] Add the entry in the appropriate section (Bug Fix / New Feature / Breaking Change / Internal Change)
  * [x] Add a period and 2 spaces at the end of your short entry description
  * [x] Add links to your GitHub profile to credit yourself ~~and to the related PR and issue after your description~~

---

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by AliSoftware — APPROVED** [review]
Thanks for the fix!

**Comment by djbe** [comment]
Note: forgot to add the issue/pr number to the changelog, need to fix that in another PR (maybe the release one).

**Comment by AliSoftware** [comment]
> Note: forgot to add the issue/pr number to the changelog, need to fix that in another PR (maybe the release one).

Nicely spotted. Added as part of https://github.com/SwiftGen/SwiftGen/pull/684 since that's likely the next one we'll merge

**Comment by Lutzifer** [comment]
thx for all your work here!

**Pull request merged**
