### PR TITLE
Fix warnings in templates caused by SwiftLint 0.51.0

### PR DESCRIPTION
**Pull request by ZevEisenberg**
* [x] I've started my branch from the `develop` branch (gitflow)
  * [x] And I've selected `develop` as the "base" branch for this Pull Request I'm about to create
* [x] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself  
      _(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
  * [x] Add the entry in the appropriate section (Bug Fix / New Feature / Breaking Change / Internal Change)
  * [x] Add a period and 2 spaces at the end of your short entry description
  * [x] Add links to your GitHub profile to credit yourself and to the related PR and issue after your description

---

Added `// swiftlint:enable all` to the bottom of all the Swift templates. Updated relevant internal tests to account for this change. Also updated the version of SwiftLint that SwiftGen uses to make sure it's compatible with the latest and greatest.

## Links

- [SwiftLint 0.51.0 release](https://github.com/realm/SwiftLint/releases/tag/0.51.0)
- Issue is caused by new [`blanket_disable_command`](https://github.com/realm/SwiftLint/pull/4731) SwiftLint rule.

### CODE REVIEW

**Comment by shagedorn** [comment]
> Should these be removed in favor of just disabling all at the top and re-enabling it at the bottom?

I wondered if `swiftlint:enable: all` would actually enable _all_ linter warnings, including those that had not been enabled before… but it seems SwiftLint is smart and essentially only re-enables those that were enabled before. At least in a custom stencil in our project, I applied this change and I'm not seeing hundreds of new warnings 😄

**Comment by ZevEisenberg** [comment]
I took the liberty of removing all superfluous disable and enable commands in the stencil files, but I can revert that if it's too big a change for one PR.

**Comment by ZevEisenberg** [comment]
It looks like I don't have permission to run Danger. Not sure how to get around that.

**Comment by ZevEisenberg** [comment]
It's not clear to me why the SwiftLint step is failing. I can't even tell which files it's complaining about 🤔

**Comment by djbe** [comment]
> I took the liberty of removing all superfluous disable and enable commands in the stencil files, but I can revert that if it's too big a change for one PR.

Ah no, wouldn't do that. In our linting step, we remove that line, so we can actually lint our generated output (to a certain extent).

**Comment by ZevEisenberg** [comment]
Rebased. It's like it was never there 😆

**Comment by ZevEisenberg** [comment]
I updated SwiftLint to 0.51.0 because I figure, if this PR is fixing something related to that release, we should actually be testing with it. Now I see that it's going to need a little more massaging to properly remove the enable commands from the stencil files for testing. But, progress.

**Comment by ZevEisenberg** [comment]
OK, I've updated the internal linting code to remove the newly-added `enable` command at the bottom during the linting phase, and updated a couple more lint failures that popped up when I ran `bundle exec rake lint:code lint:output lint:tests`.

**Comment by ZevEisenberg** [comment]
@djbe @shagedorn I think this is actually ready for full review now. I updated to SwiftLint 0.51.0 internally, and updated everything to be compatible with the new changes as far as I can tell.

**Review by ibrahimchiha — APPROVED** [review]

**Review by ihor-yarovyi — APPROVED** [review]

**Comment by eseay** [comment]
Is there anything else needed in order to merge this PR? I see that the CI check failed above, but it appears to be related to an invalid API token.

**Comment by ZevEisenberg** [comment]
Bump 😀

**Comment by ZevEisenberg** [comment]
Bump 🙃

**Comment by ZevEisenberg** [comment]
bump 😉

**Comment by Fab1n** [comment]
I am also waiting on this PR to be merged. Thanks for your work @ZevEisenberg!

**Comment by kokluch** [comment]
Can this be merged?

**Comment by mariano-mix** [comment]
For the time being, we are just ignoring this file from the linter. Hopefully this gets merged soon!

**Comment by eseay** [comment]
> For the time being, we are just ignoring this file from the linter. Hopefully this gets merged soon!

Same. We've just added all of the things in our `Generated` folder to the ignore list in our SwiftLint config. Honestly, as I think about it more, this may be the preferable long term solution. If it's generated code that no one is manually editing, I don't think I really care about the specific details of the formatting.

**Comment by vg-identance** [comment]
bump)

**Comment by martres** [comment]
Bump :)

**Comment by qwite** [comment]
Bump

**Comment by SarahDelCastillo** [comment]
Bump again!

**Comment by Liquidsoul** [comment]
Sorry for the (very) long wait 😅 

I'll try to review this as soon as I can. In the meantime, if @ZevEisenberg can rebase it, it would be awesome!

**Comment by ZevEisenberg** [comment]
Rebasèd!

**Comment by niklasamslgruber** [comment]
@ZevEisenberg any updates on this PR?

**Comment by ZevEisenberg** [comment]
Oh! I didn't realize I had dialing checks. I'll get them fixed up soon. Also, it looks like danger isn't running right on PRs?

**Comment by Liquidsoul** [comment]
The compile output job fails because of [this](https://github.com/SwiftGen/SwiftGen/pull/1107) so you might have nothing to do here but checking that could not hurt @ZevEisenberg 😉
Danger should work now though 🤔

**Comment by ZevEisenberg** [comment]
Hmm, I don’t understand what’s causing this error:

```
 xcrun --toolchain com.apple.dt.toolchain.XcodeDefault -sdk watchos swiftc -swift-version 5 -typecheck -target "armv7k-apple-watchos2.0" -I "Sources/TestUtils/Fixtures/CompilationEnvironment/swift5/watchos"  -module-name SwiftGen  Sources/TestUtils/Fixtures/Generated/XCAssets/swift5/all-allValues.swift
Sources/TestUtils/Fixtures/Generated/XCAssets/swift5/all-allValues.swift:173:4: error: stored properties cannot be marked potentially unavailable with '@available'
  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, macOS 10.13, *)
   ^
Sources/TestUtils/Fixtures/Generated/XCAssets/swift5/all-allValues.swift:193:4: error: stored properties cannot be marked potentially unavailable with '@available'
  @available(iOS 13.0, tvOS 13.0, watchOS 6.0, macOS 10.15, *)
   ^
Failed to compile Sources/TestUtils/Fixtures/Generated/XCAssets/swift5/all-allValues.swift!
```

And I can’t reproduce it in Xcode either 🤔

**Comment by ZevEisenberg** [comment]
Conveniently, here’s the exact line that causes the failure if you run it in Terminal:

```sh
xcrun --toolchain com.apple.dt.toolchain.XcodeDefault -sdk watchos swiftc -swift-version 5 -typecheck -target "armv7k-apple-watchos2.0" -I "Sources/TestUtils/Fixtures/CompilationEnvironment/swift5/watchos"  -module-name SwiftGen  Sources/TestUtils/Fixtures/Generated/XCAssets/swift5/all-allValues.swift
```

**Comment by ZevEisenberg** [comment]
Ohhh, I missed the link in your message. Should I merge in that change or wait for it to land?

**Comment by Liquidsoul** [comment]
@ZevEisenberg I have merged the fixes that should make all the jobs pass. If you can rebase one last time, I'll be happy to merge your contribution ! 👍

**Review by Liquidsoul — APPROVED** [review]

**Comment by ZevEisenberg** [comment]
Rebased!

**Pull request merged**
