### PR TITLE
Fix TemplateRef to handle empty string paths

### PR DESCRIPTION
**Pull request by djbe**
Fixes one part of #346.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Thanks!

**Comment by AliSoftware** [comment]
I'm not sure I agree with the direction of that change. I'm not a fan of defaulting to a `Path("")` then checking `path.string.isEmpty`, feels like a wrong usage of `Path`, building an invalid `Path` instance (with an empty path component) when we know that what we mean here is "no path provided"

That's why I conceptually used `Path?` here in the first place.

What about keeping that `Path?` in the init and that `nil` vs `let path?` in the `switch`… and defaulting the `templatePath` Commander option to `nil` instead (to reflect the concept of "no value provided", rather than "a value of empty string provided")? Wouldn't that be more suitable and logical?

**Comment by AliSoftware** [comment]
Ok, I tried using `Path?` but it's complicated with Commander indeed, because `Optional<Path>` doesn't conform to `ArgumentConvertible`. Dammit.

**Comment by djbe** [comment]
There's an (old) PR on Commander to add optional options (option-ception):
https://github.com/kylef/Commander/pull/48

**Comment by AliSoftware** [comment]
Good find. We might want to ping Kyle on this one.

In the meantime, I'm gonna switch the argument parsing to consider the argument as a `String` for consistency, and convert it to a `Path` manually only after Commander parsing (basically in `TemplateRef.init`). Feels more consistent than to instantiate a `Path` with empty string. Commit pending.

**Pull request merged**
