### PR TITLE
This fixes a missing semicolon in generated strings.h files.  #trivial

### PR DESCRIPTION
**Pull request by mr-fixit**
See https://github.com/SwiftGen/SwiftGen/pull/378#discussion_r368331598. Thanks, @wingeddoom

Before
``` ObjC 
+ (NSString*)privateWithValues:(id)p1 :(NSInteger)p2
```
After
``` ObjC 
+ (NSString*)privateWithValues:(id)p1 :(NSInteger)p2;
```
* [x] I've started my branch from the `develop` branch (gitflow)
  * [x] And I've selected `develop` as the "base" branch for this Pull Request I'm about to create
* [x] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself  
      _(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
  * [ ] Add the entry in the appropriate section (Bug Fix / New Feature / Breaking Change / Internal Change)
  * [ ] Add a period and 2 spaces at the end of your short entry description
  * [ ] Add links to your GitHub profile to credit yourself and to the related PR and issue after your description

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mr-fixit** [comment]
@AliSoftware @djbe any idea why CI builds are failing?

**Comment by mr-fixit** [comment]
oh, duh.  because i didn't change the unit-test.

**Comment by AliSoftware** [comment]
Ready to approve once you fix the unit tests 😃

**Comment by mr-fixit** [comment]
help!  i don’t remember how to generate new unit-test output…

**Comment by mr-fixit** [comment]
How do I fix spm-build-and-test?  Is it even my fault?


``` bash
==> libxml2
libxml2 is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have libxml2 first in your PATH run:
  echo 'export PATH="/usr/local/opt/libxml2/bin:$PATH"' >> ~/.bash_profile

For compilers to find libxml2 you may need to set:
  export LDFLAGS="-L/usr/local/opt/libxml2/lib"
  export CPPFLAGS="-I/usr/local/opt/libxml2/include"
```

**Comment by AliSoftware** [comment]
Oh no not that libxml nightmare all over again…

Depending on the macOS version and CI image, we have to install libxml2 manually as it's required to build the XML lib we use but happens to not be installed on all macOS version… So maybe only `brew install` it on images that require it (according to the error you quote, it seems that the image you use for SPM and that failed actually does have libxml2 built-in now which means you should not `brew install` it for this CI image?)

**Comment by otusweb** [comment]
My pull request (#674) to fix the same issue got merged, but I realize yours is better as you actually updated the unit tests which I did not. So please still try to get it merges.

**Comment by AliSoftware** [comment]
I'm in the process of updating Kanna to [5.2+](https://github.com/tid-kijyun/Kanna/releases/tag/5.2.0), which apparently doesn't need libxml on Xcode 11.4 and later macOS anymore and will hopefully fix that CI issue…

**Review by AliSoftware — APPROVED** [review]

**Pull request merged**
