### PR TITLE
Fix #673: add ; at the end of method declarations

### LINKED ISSUE #673: Strings: Objective-C template does not compile for entries with parameters
steps to repro:
- create a localisation with substitution (ie: "version label"="Version: %@(%@);"
- run swiftgen with the Objc template

=> .h file does not compile because semi column is missing after every string with a substitution

generated code:
`+ (NSString*)versionLabelWithValues:(id)p1 :(id)p2`

expected code:
`+ (NSString*)versionLabelWithValues:(id)p1 :(id)p2;`

Fix:
In template: add ';' at the end of line 44 and 46

### PR DESCRIPTION
**Pull request by otusweb**
* [X ] I've started my branch from the `develop` branch (gitflow)
  * [X ] And I've selected `develop` as the "base" branch for this Pull Request I'm about to create
* [X ] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself  
      _(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
  * [ X] Add the entry in the appropriate section (Bug Fix / New Feature / Breaking Change / Internal Change)
  * [ ] Add a period and 2 spaces at the end of your short entry description
  * [X ] Add links to your GitHub profile to credit yourself and to the related PR and issue after your description

---

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mr-fixit — DISMISSED** [review]
this duplicates PR #672.  i don't care which one gets merged, but neither PR gets through CI.

I'm fixing my unit-tests now...

**Comment by otusweb** [comment]
Failing on setting up the tests, i'm not sure i can do much about this

**Comment by otusweb** [comment]
Closing as this duplicates exactly #672, no need to have two of us figure out the failing build

**Pull request closed without merging**
