### PR TITLE
Fix CircleCI builds (for Xcode9 version search) + sync:all_files

### PR DESCRIPTION
**Pull request by AliSoftware**
See https://github.com/SwiftGen/templates/pull/86 — porting changes/fixes back here

### CODE REVIEW

**Comment by djbe** [comment]
If I understand this right, we don't use spotlight anymore if the version directly matches. If it doesn't, we fall back to spotlight to find one that does, right?

If so, this might probably still break when CI has Xcode 9 and 10, 9 is "selected", but we need 10.

**Comment by djbe** [comment]
Note that my previous comment is just that, not a request for change, because I don't think there's much we can do about it.

**Comment by AliSoftware** [comment]
Yeah, see the discussion with Danielle on the Slack (private messages), Circle doesn't have Spotlight enabled anymore, and even with `launchctl` this shouldn't even work (if it worked before, that's because of luck with race condition probably)

So on CI we'll always have the right Xcode version selected anyway (because `circle.yml` specified the machine to use, so this should always match and early-exit, and on other machines (like contributor's macs) at least it still uses spotlight to search for other versions as a fallback

**Comment by AliSoftware** [comment]
I'll try not to forget to apply the same on SwiftGenKit and StencilSwiftKit this evening after work 😉

**Pull request merged**
