### PR TITLE
Fix: revert code coverage

### LINKED ISSUE #719: SwiftGen 6.2.0 generates default.profraw files
I've just updated to 6.2.0 and now I'm seeing `default.profraw` files being generated whenever I run `swiftgen`. 

`default.profraw` is apparently related to code coverage and generated by LLVM.

Maybe I introduced it in https://github.com/SwiftGen/SwiftGen/commit/1695642e24a3844434020a4acc230efd9f95cb43?

### PR DESCRIPTION
**Pull request by djbe**
Fixes #719. 

Reverts #703.

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AliSoftware** [comment]
I think it should be possible to still activate code coverage for debug builds, but disable it for release builds (we use release config for our GH/CP/HB releases)?

**Comment by djbe** [comment]
@AliSoftware note that this is at the scheme level, not the config level, so I don't think that's possible.

**Comment by AliSoftware** [comment]
> @AliSoftware note that this is at the scheme level, not the config level, so I don't think that's possible.

Right. I was more thinking about using the right xcodebuild flag when compiling via rake to disable code coverage there during release 🤷🏻

**Comment by djbe** [comment]
Ah, from a quick search, that would maybe be `-enableCodeCoverage NO`. Will have to test that.

**Comment by djbe** [comment]
So, that flag doesn't work:
> The flag -enableCodeCoverage is only supported when testing.

I've also tried these to no avail:
```
CLANG_ENABLE_CODE_COVERAGE=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO
```

Can't seem to find much (anything) about disabling this from CLI.

**Comment by AliSoftware** [comment]
Ok, let's disable it completely then.

**Review by AliSoftware — APPROVED** [review]

**Pull request merged**
