### PR TITLE
Add Danger to SwiftGen

### PR DESCRIPTION
**Pull request by AliSoftware**
1. I expect it to warn me about this PR pointing to master instead of develop
2.  then once I've changed the target branch to develop appropriately, I expect it to then warn me about missing entry in CHANGELOG (not before, because the diff between feature/danger & master do contain a CHANGELOG, while there's none with develop)

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Feature branches should start from and be merged to ‘develop’</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AliSoftware** [comment]
Additional rules to add to Danger (but maybe in a separate PR later?)

* https://github.com/SwiftGen/SwiftGen/issues/230#issuecomment-387807751 : `Podfile.lock` & `Package.resolved` should be modified together
* Linting the CHANGELOG to check for the format of entries added (full-stop + 2 spaces, etc). Might need a little more work and some ruby-foo for parsing appropriately.

**Comment by AliSoftware** [comment]
Mmmh strange, on that second run according to the CI logs Danger _did_ find that there was missing a CHANGELOG entry… but she didn't post anything this time?

**Comment by SwiftGen-Eve** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Please add a CHANGELOG entry to credit your work</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
