### PR TITLE
Upgrade Xcode & Ruby versions to fix CI

### PR DESCRIPTION
**Pull request by PatrickNLT**
Builds are currently broken (see https://circleci.com/gh/SwiftGen/SwiftGen/4224)

Full config : https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-534/index.html

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Ukarin** [comment]
We heard that you lost your GitHub password. Sorry about that!

But don’t worry! You can use the following link to reset your password:

**Comment by Ukarin** [comment]
We heard that you lost your GitHub password. Sorry about that!

But don’t worry! You can use the following link to reset your password:

**Comment by djbe** [comment]
What on earth is making it try to use `2.3.7`? 😕 

`.ruby-version` clearly states `2.4.6`, and the old value was `2.4.5`, so 2.3 is not even close...

**Comment by djbe** [comment]
Wait, it's using ruby during checkout?

**Comment by djbe** [comment]
So, reason CircleCI was going bonkers is that it is somehow triggering `chruby` version auto-switching during checkout, before we've switched from `master` to this branch.
- `master` still depends on `2.3.7` (and an old 10.0.0 image)
- There is no overlap of available ruby versions between `master` and this branch
- CircleCI disabled auto-switching in the latest Catalina based images

We've decided to jump ship to the latest available image (Catalina based), and ensure it works on that one.

**Review by djbe — APPROVED** [review]

**Pull request merged**
