### PR TITLE
Bump PathKit to Fix Building on Xcode 13

### PR DESCRIPTION
**Pull request by jsorge**
* [x] I've started my branch from the `develop` branch (gitflow)
  * [x] And I've selected `develop` as the "base" branch for this Pull Request I'm about to create
* [x] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself  
      _(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
  * [ ] Add the entry in the appropriate section (Bug Fix / New Feature / Breaking Change / Internal Change)
  * [ ] Add a period and 2 spaces at the end of your short entry description
  * [ ] Add links to your GitHub profile to credit yourself and to the related PR and issue after your description

---

Bumps package dependencies to resolve build issues with Xcode 13 (the big thing is bringing in [PathKit 1.0.1](https://github.com/kylef/PathKit/releases/tag/1.0.1)).

### CODE REVIEW

**Comment by chrisballinger** [comment]
Might want to rename to "Xcode 13 Hotfix & Bump Package Dependencies" or similar so it receives more attention. 

If bumping other dependencies is too risky for the maintainers, perhaps just updating PathKit is sufficient for now. Also might make it easier to cherry-pick this change into a 6.4.1 point release, since the last release 6.4.0 was in October 2020 and `develop` might not be stable enough for a new release.

edit: I opened a hotfix PR over here: https://github.com/SwiftGen/SwiftGen/pull/875

**Comment by chrisballinger** [comment]
This PR should also update the `Package.swift` to ensure that the minimum version of `PathKit` is `1.0.1`. For other packages that pull this in as a dependency, it won't check `Package.resolved`.

**Comment by jsorge** [comment]
Good calls. I’ve updated the PR to only update PathKit both in the package manifest and the lock file.

**Review by djbe — APPROVED** [review]

**Comment by chrisballinger** [comment]
@djbe Is a quick `6.4.1` release with just this change cherry-picked into the `stable` branch in the cards? There is still a blocker to compilation on Xcode 13 until that happens

**Pull request merged**
