### PR TITLE
Escape newlines again in .strings file keys

### PR DESCRIPTION
**Pull request by ChristopherRogers**

### CODE REVIEW

**Comment by djbe** [comment]
Could you add a unit test for this (or modify existing ones? Also please add a changelog entry.

**Comment by AliSoftware** [comment]
I'm a bit surprised by that change: In which case would **keys** need newline-escaping?

**Comment by ChristopherRogers** [comment]
We have a strings file that was generated (I think) using the traditional tool that scans for uses of NSLocalizedString() and sets the key to the orgiinal translation. So if the original translation had \n in it, it remains in the key.

**Comment by AliSoftware** [comment]
Ok. Seems like a strange process to me (to have keys that are actual text potentially containing diacritics, newlines, and even potentially emojis), but that doesn't hurt to escape them for all of those who don't have them I guess 😉

There seems to be conflicts with `master` since this has been submitted though. Could you fix the conflict so we can merge this?

Also, you might want to add an entry in the CHANGELOG to credit yourself too :wink:

**Review by AliSoftware — CHANGES_REQUESTED** [review]
* Please add at least one Unit Test for this use case
* Please add an entry to mention the change and credit yourself in the CHANGELOG

**Comment by ChristopherRogers** [comment]
@djbe Thanks.

**Review by AliSoftware — APPROVED** [review]

**Pull request merged**
